config/routes.rb
MaronasApp::Application.routes.draw do
  resources :shows
  get 'slots_ext/:id' => 'slots#show_external', as: :slot_external
  resources :promotions

  resources :services

  devise_for :users
  resources :slots
  resources :servicios
  resources :promotions

  root 'welcome#index'

end

app/models/slot.rb
# == Schema Information
#
# Table name: slots
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  opentimes   :string(255)
#  address     :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Slot < ActiveRecord::Base
  has_many :promotions
  accepts_nested_attributes_for :promotions, :reject_if => :all_blank, :allow_destroy => true
  has_many :services
  accepts_nested_attributes_for :services, :reject_if => :all_blank, :allow_destroy => true
  has_many :shows
  accepts_nested_attributes_for :shows, :reject_if => :all_blank, :allow_destroy => true  
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy, :show_external]
  before_filter :authenticate_user! , except: [:index, :show, :show_external]
  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  def show_external
    
  end
  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @slot }
      else
        format.html { render action: 'new' }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:name, :opentimes, :address, :description, promotions_attributes: [:id, :name, :description, :_destroy],services_attributes: [:id, :name, :description, :_destroy],shows_attributes: [:id, :name, :description, :_destroy])
    end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_for @slot, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :opentimes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :opentimes, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div id="promotions" class="row-fluid">
    <div >
      <fieldset>
        <legend class="no-margin-bottom"><%= t('.promotions')%> <small><%=t('.promotion_message')%></small></legend>
        <table class="table table-striped  table-condensed no-margin-bottom">
          <thead>
            <tr>
              <th class="span4"><%= t('.name') %></th>
              <th class="span6"><%= t('.description') %></th>
              <th class="span2"><%= t('actions') %></th>
            </tr>
           </thead>
        </table>
        <%= f.fields_for :promotions do |exp| %>
          <%= render 'promotion_fields', :f => exp %>
        <% end %>
      </fieldset>
    </div>
    <div class="links">
      <%= link_to_add_association t('.new_promotion'), f, :promotions, :class => 'btn'%>
    </div>
  </div>
  <div id="services" class="row-fluid">
    <div >
      <fieldset>
        <legend class="no-margin-bottom"><%= t('.services')%> <small><%=t('.services_message')%></small></legend>
        <table class="table table-striped  table-condensed no-margin-bottom">
          <thead>
            <tr>
              <th class="span4"><%= t('.name') %></th>
              <th class="span6"><%= t('.description') %></th>
              <th class="span2"><%= t('actions') %></th>
            </tr>
           </thead>
        </table>
        <%= f.fields_for :services do |exp| %>
          <%= render 'service_fields', :f => exp %>
        <% end %>
      </fieldset>
    </div>
	
  <div id="shows" class="row-fluid">
    <div >
      <fieldset>
        <legend class="no-margin-bottom"><%= t('.shows')%> <small><%=t('.shows_message')%></small></legend>
        <table class="table table-striped  table-condensed no-margin-bottom">
          <thead>
            <tr>
              <th class="span4"><%= t('.name') %></th>
              <th class="span6"><%= t('.description') %></th>
              <th class="span2"><%= t('actions') %></th>
            </tr>
           </thead>
        </table>
        <%= f.fields_for :shows do |exp| %>
          <%= render 'show_fields', :f => exp %>
        <% end %>
      </fieldset>
    </div>
    <div class="links">
      <%= link_to_add_association t('.new_show'), f, :shows, :class => 'btn'%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit t('.new_slot'), :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                slots_path, :class => 'btn' %>
  </div>
<% end %>

app/views/slots/_promotion_fields.html.erb
<div class="nested-fields row-fluid" >
   <table class="table table-condensed table-bottom without-margin-bottom" >
     <tbody>
       <tr>
         <td class="span4">
           <%= f.text_field :name, :class => 'text_field' %>
         </td>
         <td class="span6 input-append">
           <%= f.text_area :description, :class => 'span12' %>
         </td>
         <td class="span2">
           <%= link_to_remove_association t('.remove'), f, :class => 'btn btn-danger btn-mini' %>
         </td>
       </tr>
     </tbody>
   </table>
 </div>

app/views/slots/_service_fields.html.erb
<div class="nested-fields row-fluid" >
   <table class="table table-condensed table-bottom without-margin-bottom" >
     <tbody>
       <tr>
         <td class="span4">
           <%= f.text_field :name, :class => 'text_field' %>
         </td>
         <td class="span6 input-append">
           <%= f.text_area :description, :class => 'span12' %>
         </td>
         <td class="span2">
           <%= link_to_remove_association t('.remove'), f, :class => 'btn btn-danger btn-mini' %>
         </td>
       </tr>
     </tbody>
   </table>
 </div>

app/views/slots/_show_fields.html.erb
<div class="nested-fields row-fluid" >
   <table class="table table-condensed table-bottom without-margin-bottom" >
     <tbody>
       <tr>
         <td class="span4">
           <%= f.text_field :name, :class => 'text_field' %>
         </td>
         <td class="span6 input-append">
           <%= f.text_area :description, :class => 'span12' %>
         </td>
         <td class="span2">
           <%= link_to_remove_association t('.remove'), f, :class => 'btn btn-danger btn-mini' %>
         </td>
       </tr>
     </tbody>
   </table>
 </div>

app/views/slots/index.html.erb
<%- model_class = Slot -%>
<!-- <div class="page-header">
  <h1><%=t '.title'%></h1>
</div> -->
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3 principal" style="padding: 0;">
      <div class="row-fluid" style="text-align:center;">
        <%= image_tag 'slots_izq.png' , size: '90%' %>
      </div>
      <div class="row-fluid">
        <table class="table table-striped span9">
            <tbody>
              <% @slots.each do |slot| %>
                <tr>
                  <td class="span12 lista" style="margin:1px , padding: 1"><%= link_to slot.name, slot_external_path(slot) %></td>
                </tr>
              <% end %>
            </tbody>
        </table>     
    </div>
  </div>
</div>

app/views/slots/new.html.erb
<%- model_class = Slot -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/slots/show.html.erb
<%- model_class = Slot -%>
<div class="page-header">
  <h1><%=t '.title' %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= t '.name' %>:</strong></dt>
  <dd><%= @slot.name %></dd>
  <dt><strong><%= t '.opentimes' %>:</strong></dt>
  <dd><%= @slot.opentimes %></dd>
  <dt><strong><%= t '.address' %>:</strong></dt>
  <dd><%= @slot.address %></dd>
  <dt><strong><%= t '.description' %>:</strong></dt>
  <dd><%= @slot.description %></dd>
</dl>

<%= field_set_tag t '.promotions', :class => 'well well_2D' do %>
  <div class="row-fluid">
    <table class="table table-striped ">
      <thead>
        <tr>
          <th width = '50%'><%= t('.promotions_name') %></th>
          <th width = '50%'><%= t('.promotions_description') %></th>
        </tr>
      </thead>
      <tbody>
        <% @slot.promotions.each do |promo| %>
          <tr>
            <td><%= promo.name %></td>
            <td><%= promo.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<%= field_set_tag t '.services', :class => 'well well_2D' do %>
  <div class="row-fluid">
    <table class="table table-striped ">
      <thead>
        <tr>
          <th width = '50%'><%= t('.services_name') %></th>
          <th width = '50%'><%= t('.services_description') %></th>
        </tr>
      </thead>
      <tbody>
        <% @slot.services.each do |service| %>
          <tr>
            <td><%= service.name %></td>
            <td><%= service.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<%= field_set_tag t '.shows', :class => 'well well_2D' do %>
  <div class="row-fluid">
    <table class="table table-striped ">
      <thead>
        <tr>
          <th width = '50%'><%= t('.shows_name') %></th>
          <th width = '50%'><%= t('.shows_description') %></th>
        </tr>
      </thead>
      <tbody>
        <% @slot.shows.each do |show| %>
          <tr>
            <td><%= show.name %></td>
            <td><%= show.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              slots_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_slot_path(@slot), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              slot_path(@slot),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/slots/show_external.html.erb
<%- model_class = Slot -%>
<div class="page-header">
  <h1><%=t '.title' %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= t '.name' %>:</strong></dt>
  <dd><%= @slot.name %></dd>
  <dt><strong><%= t '.opentimes' %>:</strong></dt>
  <dd><%= @slot.opentimes %></dd>
  <dt><strong><%= t '.address' %>:</strong></dt>
  <dd><%= @slot.address %></dd>
  <dt><strong><%= t '.description' %>:</strong></dt>
  <dd><%= @slot.description %></dd>
</dl>

<%= field_set_tag t '.promotions', :class => 'well well_2D' do %>
  <div class="row-fluid">
    <table class="table table-striped ">
      <thead>
        <tr>
          <th width = '50%'><%= t('.promotions_name') %></th>
          <th width = '50%'><%= t('.promotions_description') %></th>
        </tr>
      </thead>
      <tbody>
        <% @slot.promotions.each do |promo| %>
          <tr>
            <td><%= promo.name %></td>
            <td><%= promo.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<%= field_set_tag t '.services', :class => 'well well_2D' do %>
  <div class="row-fluid">
    <table class="table table-striped ">
      <thead>
        <tr>
          <th width = '50%'><%= t('.services_name') %></th>
          <th width = '50%'><%= t('.services_description') %></th>
        </tr>
      </thead>
      <tbody>
        <% @slot.services.each do |service| %>
          <tr>
            <td><%= service.name %></td>
            <td><%= service.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<%= field_set_tag t '.shows', :class => 'well well_2D' do %>
  <div class="row-fluid">
    <table class="table table-striped ">
      <thead>
        <tr>
          <th width = '50%'><%= t('.shows_name') %></th>
          <th width = '50%'><%= t('.shows_description') %></th>
        </tr>
      </thead>
      <tbody>
        <% @slot.shows.each do |show| %>
          <tr>
            <td><%= show.name %></td>
            <td><%= show.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              slots_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_slot_path(@slot), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              slot_path(@slot),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>