config/routes.rb
MaronasApp::Application.routes.draw do
  resources :shows
  get 'slots_ext/:id' => 'slots#show_external', as: :slot_external
  resources :promotions

  resources :services

  devise_for :users
  resources :slots
  resources :servicios
  resources :promotions

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3 principal" style="padding: 0;">
      <div class="row-fluid" style="text-align:center;">
        <%= image_tag 'menu_izq.png' , size: '90%' %>
      </div>
      <div class="row-fluid">
        <div class="span4">
          <%= link_to slots_path do %>
            <%=image_tag 'botones-01.png', class: 'botonera'%>
          <%end%>
          
        </div>
        <div class="span4">
          <%= link_to shows_path do %>
            <%=image_tag 'botones-02.png', class: 'botonera'%>
          <%end%>        
        </div>
        <div class="span4">
          <%= link_to promotions_path do %>
            <%=image_tag 'botones-03.png', class: 'botonera'%>
          <%end%>         
        </div>
      </div>
      <div class="row-fluid">
        <div class="span4">
          <%= link_to services_path do %>
            <%=image_tag 'botones-04.png', class: 'botonera'%>
          <%end%>         
        </div>
        <div class="span4">
          <%=image_tag 'botones-05.png', class: 'botonera'%>
        </div>
        <div class="span4">
          <%=image_tag 'botones-06.png', class: 'botonera'%>
        </div>
      </div>
      <div class = "row-fluid">
        <div class="span1">
          <%= image_tag 'iconos inferiores-01.png' %>
         </div>
         <div class="span1 offset7">
            <%= link_to new_user_session_path do %>
              <%= image_tag 'iconos inferiores-06.png' %>
            <%end%> -->
         </div>
      </div>      
    </div>
    <div class="span9 container-fluid" style="margin: 0;">
      <div class="row-fluid" style="text-align:center;">
        <%= image_tag 'entertainment.png', size: '300x300'%>
      </div>
      <div class="row-fluid" style="text-align:center;">
        <%= image_tag 'menu_der.png', class: 'image_principal'%>
      </div>
      <<div class="row-fluid" style="text-align:center;">
        <p style="color: white;">askfjsklfjsklfjsklfjasdkfjsdlkfjsdlkfjsdlkfjasdlkfjasdlkfjasdkfjasdflkasdjfalkdsjf</p>
      </div>
    </div>
  </div>
</div>