config/routes.rb
MaronasApp::Application.routes.draw do
  resources :shows
  get 'slots_ext/:id' => 'slots#show_external', as: :slot_external
  resources :promotions

  resources :services

  devise_for :users
  resources :slots
  resources :servicios
  resources :promotions

  root 'welcome#index'

end

app/models/promotion.rb
# == Schema Information
#
# Table name: promotions
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  slot_id     :integer
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Promotion < ActiveRecord::Base
  belongs_to :slot
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @promotion }
      else
        format.html { render action: 'new' }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params(:promotion).permit(:name,:description)
    end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% @promotion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editing promotion</h1>

<%= render 'form' %>

<%= link_to 'Show', @promotion %> |
<%= link_to 'Back', promotions_path %>

app/views/promotions/index.html.erb
<%- model_class = Promotion -%>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3 principal" style="padding: 0;">
      <div class="row-fluid" style="text-align:center;">
        <%= image_tag 'promos_izq.png' , size: '90%' %>
      </div>
      <div class="row-fluid">
        <table class="table table-striped span9">
            <tbody>
              <% @promotions.each do |promotion| %>
                <tr>
                  <td class="span12 lista" style="margin:1px , padding: 1"><%= promotion.name %></td>
                </tr>
              <% end %>
            </tbody>
        </table>     
    </div>
  </div>
</div>

app/views/promotions/new.html.erb
<h1>New promotion</h1>

<%= render 'form' %>

<%= link_to 'Back', promotions_path %>

app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_promotion_path(@promotion) %> |
<%= link_to 'Back', promotions_path %>